### ISSUE TITLE
Without hashing, file name too long

### ISSUE THREAD

**Issue by damienchallet** [sarenehan/cache_to_disk#5]
Since commit 08fc5e36e0ae647b9400128a95114ae5c14c2063, the filename of a dataframe is likely to become too large. Please add an option to hash the input data so that this is not an issue.

**Comment by phseidl** [comment]
a quick fix is to input the hash, to the function and get the actual value via the global variable

**Comment by ri0t** [comment]
An alternative that might work for you:
Cache less complex structures, instead choose more atomic data. I've redesigned my cached function to only cache one bit of a list instead of the whole ordeal. Helps.

**Comment by sarenehan** [comment]
@damienchallet This is fixed with the latest version. The function arguments, and function name are no longer used in the name of the file that stores the output of a function. Instead, these are stored in a metadata json file.

**Comment by damienchallet** [comment]
Many thanks for your fix!
